if(typeof PXA_load_start_1_2_8==='undefined'){const PXA_load_start_1_2_8=async()=>{if(window.PXA_load){return}
window.PXA_load=!0;if(typeof window.pixel_x_app==='object'||window.hasOwnProperty('pixel_x_app')){return}
async function initPixelXApp(){const pxa_start={domain:'nagelakeoma.com.br',api_event:'https://nagelakeoma.com.br/wp-json/pixel-x-app/v1/event',api_lead:'https://nagelakeoma.com.br/wp-json/pixel-x-app/v1/lead',phone_country:''||undefined,phone_valid:''||!1,phone_update:''||!1,web_priority:'1'||!1,fb_js:'https://nagelakeoma.com.br/wp-content/plugins/pixel-x-app/assets/js/pxa-fb.js?version=1.2.8',fb_pixels:'608887786815566',page_id:'42112'||document.currentScript?.getAttribute('data-page-id'),page_title:'Encontro Nacional Mulheres de Negócios 2026'||document.currentScript?.getAttribute('data-page-name'),input_custom_name:''||undefined,input_custom_email:''||undefined,input_custom_phone:''||undefined,phone_mask:'+{55} (00) [9]0000-0000',phone_mask_js:'https://nagelakeoma.com.br/wp-content/plugins/pixel-x-app/assets/libs/imask/imask.js?version=1.2.8',};window.pixel_x_app=new PixelXApp();await window.pixel_x_app.start(pxa_start).catch((error)=>{console.error('Erro ao iniciar PixelXApp:',error)});await window.pixel_x_app.parameters_load();const PXA_click_36738=async()=>{document.querySelectorAll('.SfrilaRPdjldlAJlpqLq, #SfrilaRPdjldlAJlpqLq').forEach(function(el){el.addEventListener('click',async()=>{await window.pixel_x_app.send_event({event_id:'a14d8dd2-639b-4971-8f71-50c1e5d45c3a',event_name:'Lead',page_id:'42112',page_title:'Encontro Nacional Mulheres de Negócios 2026',currency:'BRL',})})})}
await PXA_click_36738();await window.pixel_x_app.elementor_function(PXA_click_36738);const PXA_form_submit_30688=async(el)=>{if(window.pixel_x_app.check_values(el)){await window.pixel_x_app.send_event({event_id:'431c09c6-260b-487b-8583-3e477f6b956a',event_name:'Contact',page_id:'42112',page_title:'Encontro Nacional Mulheres de Negócios 2026',currency:'BRL',})}}
const PXA_form_30688=async()=>{document.querySelectorAll('.wuxAFHTxApsNYNawRQTn, #wuxAFHTxApsNYNawRQTn').forEach(async(el)=>{if(el.tagName==='FORM'&&!el.classList.contains('pxa_tracked')){el.classList.add('pxa_tracked');el.addEventListener('submit',async(e)=>{await PXA_form_submit_30688(el)})}else{const form_30688=el.querySelector('form');if(form_30688&&!form_30688.classList.contains('pxa_tracked')){form_30688.classList.add('pxa_tracked');form_30688.addEventListener('submit',async(e)=>{await PXA_form_submit_30688(form_30688)})}}
el.querySelectorAll('.e_formulario .gpc_botao').forEach(async(button)=>{if(!button.classList.contains('pxa_button_form_monitor')){button.classList.add('pxa_button_form_monitor');button.addEventListener('click',async()=>{await PXA_form_submit_30688(el)})}})})}
await PXA_form_30688();setInterval(async()=>{await PXA_form_30688()},1000);await window.pixel_x_app.elementor_function(PXA_form_30688);const PXA_click_30119=async()=>{document.querySelectorAll('.GtGtKxixMiWwKUKkNtoY, #GtGtKxixMiWwKUKkNtoY').forEach(function(el){el.addEventListener('click',async()=>{await window.pixel_x_app.send_event({event_id:'d439536f-7448-4e97-8d38-cecf9ef891a7',event_name:'AddToCart',page_id:'42112',page_title:'Encontro Nacional Mulheres de Negócios 2026',currency:'BRL',})})})}
await PXA_click_30119();await window.pixel_x_app.elementor_function(PXA_click_30119);const PXA_form_submit_18857=async(el)=>{if(window.pixel_x_app.check_values(el)){await window.pixel_x_app.send_event({event_id:'74f27de9-5783-4031-97e2-282b80fdbbfb',event_name:'Lead',page_id:'42112',page_title:'Encontro Nacional Mulheres de Negócios 2026',currency:'BRL',})}}
const PXA_form_18857=async()=>{document.querySelectorAll('.DblcMzvrWzpdEKIdVLnC, #DblcMzvrWzpdEKIdVLnC').forEach(async(el)=>{if(el.tagName==='FORM'&&!el.classList.contains('pxa_tracked')){el.classList.add('pxa_tracked');el.addEventListener('submit',async(e)=>{await PXA_form_submit_18857(el)})}else{const form_18857=el.querySelector('form');if(form_18857&&!form_18857.classList.contains('pxa_tracked')){form_18857.classList.add('pxa_tracked');form_18857.addEventListener('submit',async(e)=>{await PXA_form_submit_18857(form_18857)})}}
el.querySelectorAll('.e_formulario .gpc_botao').forEach(async(button)=>{if(!button.classList.contains('pxa_button_form_monitor')){button.classList.add('pxa_button_form_monitor');button.addEventListener('click',async()=>{await PXA_form_submit_18857(el)})}})})}
await PXA_form_18857();setInterval(async()=>{await PXA_form_18857()},1000);await window.pixel_x_app.elementor_function(PXA_form_18857);await window.pixel_x_app.send_event({event_id:'5b1b04a5-cc71-4907-9104-5ed8f6191c67',event_name:'PageView',page_id:'42112',page_title:'Encontro Nacional Mulheres de Negócios 2026',currency:'BRL',})}
if(typeof PixelXApp==='undefined'){const script=document.createElement('script');script.src='https://nagelakeoma.com.br/wp-content/plugins/pixel-x-app/assets/js/pxa-base.min.js?version=1.2.8';script.onload=async()=>{await initPixelXApp()};document.head.appendChild(script)}else{await initPixelXApp()}}
window.PXA_load=!1;document.addEventListener('DOMContentLoaded',async()=>{await PXA_load_start_1_2_8()},!1);document.addEventListener('load',async()=>{await PXA_load_start_1_2_8()},!1);setTimeout(async()=>{await PXA_load_start_1_2_8()},1000)}